name: ca_joue
description: "A new Flutter project."
publish_to: "none"
version: 0.1.2+3

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.2.3
  go_router: ^17.1.0
  google_fonts: ^8.0.1
  lucide_icons: ^0.257.0
  path: ^1.9.0
  path_provider: ^2.1.5
  riverpod_annotation: ^3.0.3
  sqflite: ^2.4.2

dev_dependencies:
  build_runner: ^2.10.5
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.3
  sqflite_common_ffi: ^2.3.4+4
  very_good_analysis: ^10.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/
